### ISSUE TITLE
CreateSnapshotPolicyで&{false  0 0   }が返却される

### ISSUE THREAD

**Issue by ghost** [uesyn/gokcps#3]
CreateSnapshotPolicy実行後、定期スナップショットの設定に成功しているにも関わらず、返り値（CreateSnapshotPolicyResponse型）が&{false  0 0   }となっています。errの方はnilです。

**Comment by uesyn** [comment]
createSnapshotPolicyで返されたJSONがsnapshotpolicyというkeyの中に実際のpolicyに関する情報が入っていたのですが、その解析が上手くできていない状態でした。
