### ISSUE TITLE
リファレンスに書かれていないコマンドのパラメータにも対応する

### ISSUE THREAD

**Issue by ghost** [uesyn/gokcps#5]
KCPSのAPIコマンドのリファレンスに書いていないパラメータもセットできるようにしてほしいです。

以下に現在確認しているリファレンスに書かれていないパラメータ一覧を示します（パラメータを全て網羅するには仕様書でも読まないと厳しい）

コマンド | パラメータ | 型 | デフォルト値 | 内容
-- | -- | -- | -- | --
createPortForwardingRule | openfirewall | bool | true | ポートフォワードのルール作成時、自動でFirewallのルールを追加するかどうか。作成されるFirewallのルールはcidrが0.0.0.0/0、portの範囲はポートフォワードのルールのパブリックポートと同じ範囲になる。
registerTemplate | details[n].nicAdapter | string | nil | NICアダプタの設定（例: details[0].nicAdapter=E1000）
registerTemplate | details[n].keyboard | string | nil | keyboardの設定（例: details[0].keyboard=us）
createTemplate | ispublic | bool | false | テンプレートの公開設定
createSnapshot | quiescevm | bool | false | VMの休止
createVMSnapshot | snapshotmemory | bool | false | メモリを含めるか否か
createLoadBalancerRule | openfirewall | bool | true | ポートフォワードのルール作成時、自動でFirewallのルールを追加するかどうか

**Comment by uesyn** [comment]
基本的にAPI referenceに掲載されていないoptionは使用できないかKCPS側で保証されないオプションになっています。
openfirewallについてはKCPSのweb上からも叩かれていたり、ispublicはTemplateのAPIで利用できるため、https://github.com/uesyn/gokcps/issues/6 で実装しましたが、他項目については、今後のKCPSのAPIのアップデートを見て実装の可否を決めさせてください。
